// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
    title,
    description,
    price
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, title, status, description, price
`

type CreateListingParams struct {
	Title       string
	Description pgtype.Text
	Price       pgtype.Int8
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing, arg.Title, arg.Description, arg.Price)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Description,
		&i.Price,
	)
	return i, err
}
