// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID          int64
	Title       string
	Status      string
	Description pgtype.Text
	Price       pgtype.Int8
}

type ListingPublication struct {
	ListingID int64
}
