// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateListing(ctx context.Context, title string) (CreateListingRow, error)
	CreateListingPublication(ctx context.Context, listingID int64) error
	GetListingForPublicationReadiness(ctx context.Context, id int64) (GetListingForPublicationReadinessRow, error)
	GetListingStatus(ctx context.Context, id int64) (string, error)
	MarkListingPublished(ctx context.Context, id int64) (MarkListingPublishedRow, error)
	UpdateListingDescription(ctx context.Context, arg UpdateListingDescriptionParams) (UpdateListingDescriptionRow, error)
}

var _ Querier = (*Queries)(nil)
