// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
}

var _ Querier = (*Queries)(nil)
